// Pure renderers for the Swift files the share extension compiles.
// Kept free of fs so they can be snapshot-tested.

import { parsePath, type PathCommand } from '../../src/design/doodles/pathParser';

const HEADER = '// GENERATED by scripts/gen-swift.ts — do not edit.\n';

export function parseColor(value: string): { r: number; g: number; b: number; a: number } {
  const hex = /^#([0-9a-f]{6})$/i.exec(value);
  if (hex) {
    const n = parseInt(hex[1], 16);
    return { r: (n >> 16) & 255, g: (n >> 8) & 255, b: n & 255, a: 1 };
  }
  const rgba = /^rgba\((\d+),\s*(\d+),\s*(\d+),\s*([\d.]+)\)$/i.exec(value);
  if (rgba) {
    return { r: +rgba[1], g: +rgba[2], b: +rgba[3], a: +rgba[4] };
  }
  throw new Error(`Unsupported color "${value}"`);
}

const fmt = (n: number) => (Math.round(n * 1000) / 1000).toString();

export function renderThemeSwift(colors: Record<string, string>, fonts: Record<string, string>): string {
  const colorLines = Object.entries(colors).map(([name, value]) => {
    const { r, g, b, a } = parseColor(value);
    return `    static let ${name} = Color(.sRGB, red: ${fmt(r / 255)}, green: ${fmt(g / 255)}, blue: ${fmt(b / 255)}, opacity: ${fmt(a)}) // ${value}`;
  });
  const fontLines = Object.entries(fonts).map(
    ([name, ps]) => `    static func ${name}(_ size: CGFloat) -> Font { .custom("${ps}", fixedSize: size) }`,
  );
  return `${HEADER}import SwiftUI

enum ReadrColor {
${colorLines.join('\n')}
}

enum ReadrFont {
${fontLines.join('\n')}
}
`;
}

function commandToSwift(c: PathCommand): string {
  switch (c.op) {
    case 'M':
      return `p.move(to: CGPoint(x: ${c.x}, y: ${c.y}))`;
    case 'L':
      return `p.addLine(to: CGPoint(x: ${c.x}, y: ${c.y}))`;
    case 'Q':
      return `p.addQuadCurve(to: CGPoint(x: ${c.x}, y: ${c.y}), control: CGPoint(x: ${c.x1}, y: ${c.y1}))`;
    case 'C':
      return `p.addCurve(to: CGPoint(x: ${c.x}, y: ${c.y}), control1: CGPoint(x: ${c.x1}, y: ${c.y1}), control2: CGPoint(x: ${c.x2}, y: ${c.y2}))`;
    case 'Z':
      return 'p.closeSubpath()';
  }
}

export function renderDoodlesSwift(data: {
  viewBox: number;
  doodles: { name: string; paths: string[] }[];
}): string {
  const entries = data.doodles.map((d) => {
    const paths = d.paths.map((path) => {
      const body = parsePath(path).map((c) => `            ${commandToSwift(c)}`).join('\n');
      return `        Path { p in\n${body}\n        }`;
    });
    return `    // ${d.name}\n    [\n${paths.join(',\n')}\n    ]`;
  });
  return `${HEADER}import SwiftUI

/// Doodle strokes in a ${data.viewBox}×${data.viewBox} space. Index = article doodle index.
enum Doodles {
  static let viewBox: CGFloat = ${data.viewBox}
  static let names: [String] = [${data.doodles.map((d) => `"${d.name}"`).join(', ')}]
  static let all: [[Path]] = [
${entries.join(',\n')}
  ]
}
`;
}
