// Bundles the shared TS for the three non-Metro runtimes:
//   core.js             → JavaScriptCore in the share extension (global ReadrCore)
//   extract.js          → web views: extension off-screen + app ExtractorHost (global ReadrExtract)
//   SafariPreprocess.js → Safari page preprocessing (global ExtensionPreprocessingJS)
import { buildSync } from 'esbuild';
import { mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';

const root = join(__dirname, '..');
const shareOut = join(root, 'targets/share/generated');
const appOut = join(root, 'src/sync/generated');
mkdirSync(shareOut, { recursive: true });
mkdirSync(appOut, { recursive: true });

const common = {
  bundle: true,
  format: 'iife' as const,
  platform: 'browser' as const,
  minify: true,
  legalComments: 'none' as const,
};

// JavaScriptCore on iOS 18 supports ES2022; BigInt is required by the id hash.
buildSync({ ...common, entryPoints: [join(root, 'src/core/index.ts')], globalName: 'ReadrCore', target: 'safari16', outfile: join(shareOut, 'core.js') });
buildSync({ ...common, entryPoints: [join(root, 'src/extract/entry.ts')], globalName: 'ReadrExtract', target: 'safari16', outfile: join(shareOut, 'extract.js') });
buildSync({ ...common, entryPoints: [join(root, 'src/extract/safariPreprocess.ts')], globalName: 'ExtensionPreprocessingJS', target: 'safari16', outfile: join(shareOut, 'SafariPreprocess.js') });

// The app's retry ExtractorHost injects the same extract bundle as a string.
const extractSource = readFileSync(join(shareOut, 'extract.js'), 'utf8');
writeFileSync(
  join(appOut, 'extractSource.ts'),
  `// GENERATED by scripts/build-bundles.ts — do not edit.\nexport const extractSource = ${JSON.stringify(extractSource)};\n`,
);

console.log('build-bundles: core.js, extract.js, SafariPreprocess.js →', shareOut);
